# Generated by Django 4.2.4 on 2023-10-20 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_login", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[],
        ),
    ]
